### ISSUE TITLE
Retire/migrate bot

### ISSUE THREAD

**Issue by mattkerlogue** [mattkerlogue/narrowbotR#1]
[botsinspace is closing](https://muffinlabs.com/posts/2024/10/29/10-29-rip-botsin-space/), choices:

1. retire the bot a la matt-dray/londonmapbot#18
2. migrate to other mastodon instance
3. migrate to bsky

**Comment by andypiper** [comment]
Would love to see this migrate to another Mastodon instance! FWIW I moved an account from botsin.space to mastodon.social with no issues, YMMV.

**Comment by mattkerlogue** [comment]
Hi @andypiper thanks for the interest and the heads up re mastodon.socal. Have had a few busy months but been planning to look into migration over the festive period.

**Comment by mattkerlogue** [comment]
Transition complete, narrowbotr has been migrated to:

- Mastodon Social - https://mastodon.social/@narrowbotr
- Bluesky - https://bsky.app/profile/narrowbotr.bsky.social
